baseURL = "http://localhost:1313/"
languageCode = "pt-br"
title = "Sociedade de Vera Cruz"
disableKinds = ["taxonomy", "term"] # Simplifica o build inicial

[params]
    # NOME COMPLETO DO BRANDING
    brand_name = "Sociedade de Vera Cruz"
    
    # SLOGAN/DESCRIÇÃO
    tagline = "idem velle, idem nolle"
    
    # Cores do Branding (Refletindo a estética Dark Classic)
    color_primary = "#8C1C1C" # Deep Red
    color_secondary = "#C8AA6E" # Antique Gold
    color_background = "#141210" # Dark Sober
    color_text = "#E7E5E4" # Off-White

[permalinks]
    artigos = "/artigos/:year/:slug/"
    producoes = "/producoes/:slug/"
    sobre = "/sobre/"
    