baseURL = "/"  # O Netlify ajusta automaticamente para o domínio correto
languageCode = "pt-br"
title = "Sociedade de Vera Cruz"
disableKinds = ["taxonomy", "term"] # Simplifica o build inicial

# Configurações de build
enableRobotsTXT = true
enableGitInfo = false

[params]
    # NOME COMPLETO DO BRANDING
    brand_name = "Sociedade de Vera Cruz"
    
    # SLOGAN/DESCRIÇÃO
    tagline = "Promoção de Artigos, Estudos e Membros Notáveis em Go."
    description = "Sociedade dedicada à promoção de artigos, estudos e membros notáveis na área de Go e desenvolvimento."
    
    # Cores do Branding
    color_primary = "#0D3E62" 
    color_secondary = "#C3B173"
    color_background = "#F9F9F9" 
    color_text = "#333333"

[permalinks]
    artigos = "/artigos/:year/:slug/"
    estudos = "/estudos/:slug/"

# Configurações de minificação para produção
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false